### PR TITLE
Create 18698.md

### PR DESCRIPTION
**Pull request by zvicklan**
Adding file for 18-698 Neural Signal Processing

# Summary of Changes

- Please indicate the classes you are modifying:
  - 18-698 - Neural Signal Processing

# Checklist:

Make sure that your contributions:

- [x] Are accurate and will not mislead the reader
- [x] Do not encourage or cause academic integrity violations
- [x] Do not offend professors or unfairly criticize the university

### CODE REVIEW

**Review by mikinty — COMMENTED** [review]
Can you please remove the extra lines at the end

**Review by mikinty — CHANGES_REQUESTED** [review]
Can you please add the class to the table of contents

**Comment by zvicklan** [comment]
Removed white space and added 18-698 to TOC

**Review by mikinty — APPROVED** [review]
Thanks!

**Comment by zvicklan** [comment]
Thank you, Michael! Sorry for the mess haha.

Best,
Zach

**Pull request merged**
