### PR TITLE
18865 Link

### PR DESCRIPTION
**Pull request by jasonatptld**
Added link for 18865 that I created in electives folder.

### CODE REVIEW

**Comment by jasonatptld** [comment]
Not sure if I entered the link correctly.  I get a 404 error when trying to follow the link.  I'm not sure if that is because the fork hasn't been merged, of if I made a mistake.

**Comment by mikinty** [comment]
You don't want to do 2 pull requests, just do it in one (edit both files in the previous PR please)

**Comment by mikinty** [comment]
Please look at some of the previous merged PRs

**Comment by jasonatptld** [comment]
Greetings,

I'm a bit lost at this point.  Is there anything else I need to do to get my entry for 18-865 added to the repository?

**Pull request closed without merging**
