### PR TITLE
Add 11642.md

### PR DESCRIPTION
**Pull request by Uranusmiko**
# Summary of Changes

- Please indicate the classes you are modifying:
  - 11-642
  - ...

# Checklist:

- [ ] I have added my entries to the `README.md` table of contents in the root directory as links.

Make sure that your contributions:

- [ ] Are accurate and will not mislead the reader
- [ ] Do not encourage or cause academic integrity violations
- [ ] Do not offend professors or unfairly criticize the university

### CODE REVIEW

**Review by b-joel-gonzalez — CHANGES_REQUESTED** [review]
This looks great! One thing though - can you add the course to the electives list in the README.md [file](https://github.com/Uranusmiko/CMU-ECE-CS-Guide/blob/Uranusmiko-patch-2/README.md)?

**Comment by Uranusmiko** [comment]
Thank you for youre reply. I have opened another pull request for updating the electives list. Is that OK?

**Comment by Uranusmiko** [comment]
I got that. I have updated elective list in this pull request. You can ignore the other pull request.

**Review by b-joel-gonzalez — APPROVED** [review]
This looks great!

**Comment by b-joel-gonzalez** [comment]
Great work!

**Pull request merged**
